### ISSUE TITLE
Add Google

### ISSUE THREAD

**Issue by hicallmeal** [jdavis/twofactorauth#8115] opened 2024-06-22 16:04 UTC
### Site name

I think core sites, such as Google/Microsoft should be represented better - currently neither are properly represented (they're indexed under own service/s or aliases). 

This certainly isn't a novel request, I've read up on #35 #208 and #1831 (+ referenced within), but I haven't seen it properly addressed. 

These core businesses are the issuers/providers of the authentication flow/framework for their products and services, so seeing 5+ Google services, but no Google entry is a little odd. (But I can see some merit in listing those services, and them being continually added).

Essentially, I propose a 'Google' entry is added (perhaps to 'Other', like MS 365) and 'Microsoft 365' reclassified as 'Microsoft' (happy to submit a separate issue for that). Same goes for Yahoo.

I apologise, I can't think of other core services like these 3, but I'm sure there are some other cases. 
It also makes me wonder if some scrutiny/pushback is warranted for services, as there can then be _n_ entries for a given company. 
Again, I can understand why: a user might search for a service, rather than the provider, but then, they _are_ still signing in using the provider... so the onus _really_ falls on them. 

Plus, additional services require further maintenance (but that's not my place to say) and can cause variance between services.

**Comment by hicallmeal** [comment] 2024-06-22 16:29
Actually, I can see there's some discussion here - #3707 and here https://github.com/2factorauth/twofactorauth/discussions/7165

I can't say I've thought about a schema solution to the identity provider situation, I could suggest the following (just to contribute _somehow_)? 

```javascript
{
    "Google": {
    "domain": "google.com",
    "additional-domains*": [
      "google.ch",
      ".."
    ],
   "services/products**": [
     "Nest", "Docs", "Foo", "bar"
    ],
    "tfa": [
      "sms",
      "email"
    ],
    "documentation": "doc/link",
    "categories": [
      "Other***"
    ],
    "regions": [
      "global"
    ]
  }
}
``` 


**\*** I'd even go as far as to propose current service domains are simply added to the 'additional-domains' for indexing
**\*\*** Could be either or something else
**\*\*\***  a _current_ category, of course there may be a better/new one

There can then be some UI element to indicate the services/products to a user. 
Such entries would still be indexed by their services (either via additional-domains or this new _services_ key), meaning no value is lost, a experience remains the same. 

Lastly, it's an optional key, like 'additional-domains'

---

Regardless of the above, I still believe Google should get an entry, and Yahoo & Microsoft's should be updated.

**Comment by Carlgo11** [comment] 2024-06-22 17:42
Duplicate of #6185

@hicallmeal thanks for your suggestion. You're very welcome to create a pull request for your suggested schema changes 🙂

**Closed as not planned by Carlgo11** 2024-06-22 17:42 UTC
Labels: duplicate, feature
