### ISSUE TITLE
Alexa.com end of service

### ISSUE THREAD

**Issue by ghost** [jdavis/twofactorauth#6529] opened 2022-02-16 23:25 UTC
On May 1, 2022, Alexa.com will be shutting down its service([source](https://support.alexa.com/hc/en-us/articles/4410503838999)).
We will need to come up with an alternative metric.

**Comment by Carlgo11** [comment] 2022-02-17 00:49
Duplicate of #6339

**Closed as completed by Carlgo11** 2022-02-17 00:49 UTC
Labels: duplicate
